export enum StyleType {
  ANIMATION = 'ANIMATION',
  BORDER = 'BORDER',
  BACKGROUND = 'BACKGROUND',
  HEIGHT = 'HEIGHT',
  TEXT_COLOR = 'TEXT_COLOR',
  TEXT_SIZE = 'TEXT_SIZE',
  TEXT_ALIGN = 'TEXT_ALIGN',
}
